### ISSUE TITLE
ULAN supported ?

### ISSUE THREAD

**Issue by antoinecourtin** [UCSCLibrary/GettySuggest#7]
Thank you for this plugin.
With the publication of the ULAN in LOD there a few weeks, do you plan to integrate it in this plugin?

Thank you in advance,

Antoine

**Comment by NedHenry** [comment]
We certainly do plan to add support for ULAN to the GettySuggest plugin.
You can expect an upgraded version of the plugin within the next 2-6 weeks,
depending on our other development priorities.

All the best,

Ned Henry

Digital Library Developer
UC Santa Cruz

**Comment by antoinecourtin** [comment]
Thank you very much for your quick and positive response !
It's a good news !

**Comment by NedHenry** [comment]
A new version of the GettySuggest plugin is now online supporting the Union List of Artist Names! We will update the plugin again when the linked data endpoint for the Culture Objects Name Authority comes online.
