### ISSUE TITLE
ULAN does not work, AAT mixed with TGN ?

### ISSUE THREAD

**Issue by LaBOdeMarie** [UCSCLibrary/GettySuggest#8]
Hello,

I don't know if this plugin is still updated. I wanted to use it for a catalogue of artworks but it seems that it does not work correctly : the ULAN shows nothing and the AAT shows choices of the TGN but not from the AAT... Is there something to change in the code or ?...
Thank you for your reply !

Best Regards,
Marie Guérinel

**Comment by NedHenry** [comment]
Thanks for reporting this bug, Marie! This plugin is updated rarely, and
these getty vocabulary endpoints are new and changing quickly. We rely on
users like you to report problems like these (thank you!). We are somewhat
short on development resources at the moment, so don't have time to find a
solution immediately, but we hope to address the issue within 1 to 2
months. I will keep you posted on our progress, and hopefully the plugin
will be useful to you once it is fixed.
Best,
Ned

**Comment by NedHenry** [comment]
I have found and fixed the problem. It was indeed a bug in the code. I apologize for the trouble! I have released a new version of the plugin that fixes this.
